[package]
name = "delegation-mock-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dev-dependencies]

[dependencies.delegation-mock]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.54.6"
