// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           51
// Async Callback:                       1
// Promise callbacks:                    5
// Total number of exported functions:  59

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    liquid_staking
    (
        init => init
        upgrade => upgrade
        delegate => delegate
        unDelegate => un_delegate
        withdraw => withdraw
        registerLsToken => register_ls_token
        registerUnstakeToken => register_unstake_token
        setStateActive => set_state_active
        setStateInactive => set_state_inactive
        setAccumulatorContract => set_accumulator_contract
        setFees => set_fees
        setMinimumRounds => set_minimum_rounds
        setMaxDelegationAddresses => set_max_delegation_addresses
        setMaxSelectedProviders => set_max_selected_providers
        setUnbondPeriod => set_unbond_period
        setManagers => set_managers
        removeManager => remove_manager
        cleanUnbondEpochs => clean_unbond_epochs
        fees => fees
        getAccumulatorContract => accumulator_contract
        roundsPerEpoch => rounds_per_epoch
        minimumRounds => minimum_rounds
        getState => state
        getLsTokenId => ls_token
        getLsSupply => ls_token_supply
        getVirtualEgldReserve => virtual_egld_reserve
        getRewardsReserve => rewards_reserve
        getTotalWithdrawnEgld => total_withdrawn_egld
        getUnstakeTokenId => unstake_token
        getPendingEGLDForDelegate => pending_egld
        getPendingEGLDForUnDelegate => pending_egld_for_unstake
        getPendingEgldForUnbond => pending_egld_for_unbond
        getUnstakeTokenNonce => unstake_token_nonce
        maxDelegationAddresses => max_delegation_addresses
        maxSelectedProviders => max_selected_providers
        unbondPeriod => unbond_period
        getDelegationAddressesList => delegation_addresses_list
        getDelegationContractInfo => delegation_contract_data
        getManagers => managers
        delegatePending => delegate_pending
        unDelegatePending => un_delegate_pending
        withdrawPending => withdraw_pending
        claimRewards => claim_rewards
        delegateRewards => delegate_rewards
        canExecutePendingTasks => can_execute_pending_tasks
        getLsValueForPosition => get_ls_value_for_position
        getEgldPositionValue => get_egld_position_value
        getExchangeRate => get_exchange_rate
        getDelegationContractStakedAmount => get_delegation_contract_staked_amount
        getDelegationContractUnstakedAmount => get_delegation_contract_unstaked_amount
        whitelistDelegationContract => whitelist_delegation_contract
        changeDelegationContractAdmin => change_delegation_contract_admin
        changeDelegationContractParams => change_delegation_contract_params
        remove_liquidity_callback => remove_liquidity_callback
        add_liquidity_callback => add_liquidity_callback
        withdraw_tokens_callback => withdraw_tokens_callback
        claim_rewards_callback => claim_rewards_callback
        delegate_rewards_callback => delegate_rewards_callback
    )
}

multiversx_sc_wasm_adapter::async_callback! { liquid_staking }
