// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           43
// Async Callback:                       1
// Promise callbacks:                    5
// Total number of exported functions:  50

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    liquid_staking
    (
        init => init
        delegate => delegate
        unDelegate => un_delegate
        withdraw => withdraw
        registerLsToken => register_ls_token
        registerUnstakeToken => register_unstake_token
        setStateActive => set_state_active
        setStateInactive => set_state_inactive
        setAccumulatorContract => set_accumulator_contract
        setFees => set_fees
        setRoundsPerEpoch => set_rounds_per_epoch
        setMinimumRounds => set_minimum_rounds
        fees => fees
        getAccumulatorContract => accumulator_contract
        roundsPerEpoch => rounds_per_epoch
        minimumRounds => minimum_rounds
        getState => state
        getLsTokenId => ls_token
        getLsSupply => ls_token_supply
        getVirtualEgldReserve => virtual_egld_reserve
        getRewardsReserve => rewards_reserve
        getTotalWithdrawnEgld => total_withdrawn_egld
        getUnstakeTokenId => unstake_token
        getPendingEgld => pending_egld
        getPendingLsForUnstake => pending_ls_for_unstake
        getUnstakeTokenNonce => unstake_token_nonce
        getDelegationAddressesList => delegation_addresses_list
        getDelegationClaimStatus => delegation_claim_status
        maxDelegationAddresses => max_delegation_addresses
        getDelegationContractData => delegation_contract_data
        delegatePending => delegate_pending
        unDelegatePending => un_delegate_pending
        withdrawPending => withdraw_pending
        claimRewards => claim_rewards
        delegateRewards => delegate_rewards
        canExecutePendingTasks => can_execute_pending_tasks
        getLsValueForPosition => get_ls_value_for_position
        getDelegationStatus => get_delegation_status
        getDelegationContractStakedAmount => get_delegation_contract_staked_amount
        getDelegationContractUnstakedAmount => get_delegation_contract_unstaked_amount
        updateMaxDelegationAddressesNumber => update_max_delegation_addresses_number
        whitelistDelegationContract => whitelist_delegation_contract
        changeDelegationContractAdmin => change_delegation_contract_admin
        changeDelegationContractParams => change_delegation_contract_params
        remove_liquidity_callback => remove_liquidity_callback
        add_liquidity_callback => add_liquidity_callback
        withdraw_tokens_callback => withdraw_tokens_callback
        claim_rewards_callback => claim_rewards_callback
        delegate_rewards_callback => delegate_rewards_callback
    )
}

multiversx_sc_wasm_adapter::async_callback! { liquid_staking }
