[package]
name = "liquid-staking-abi"
version = "0.0.0"
authors = ["Mihai Eremia <mihai@xoxno.com>"]
edition = "2021"
publish = false

[dependencies.liquid-staking]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.55.0"
