[settings]
main = "main"

[contracts.main]
name = "delegation-mock"

[contracts.full]
name = "delegation-mock-full"
add-unlabelled = true
add-labels = ["delegation-mock-external-view"]

[contracts.view]
name = "delegation-mock-view"
external-view = true
add-unlabelled = false
add-labels = ["delegation-mock-external-view"]

[[proxy]]
path = "src/proxy_delegation.rs"

[[proxy]]
path = "../liquid-staking/src/proxy/proxy_delegation.rs"

[[proxy]]
path = "../delegation-manager-mock/src/proxy_delegation.rs"