[contracts.main]
name = "delegation-mock"

[[proxy]]
path = "src/proxy_delegation.rs"

[[proxy]]
path = "../liquid-staking/src/proxy/proxy_delegation.rs"

[[proxy]]
path = "../delegation-manager-mock/src/proxy_delegation.rs"